// list all the allowed block sizes here as allow_block_size(ldA, ldB);
allow_block_size( 4, 4);
allow_block_size( 4, 5);
allow_block_size( 4, 8);
allow_block_size( 4,32);
allow_block_size( 8, 8);
allow_block_size( 8, 9);
allow_block_size( 8,10);
allow_block_size( 8,32);
allow_block_size( 8,64);
allow_block_size(16,16);
allow_block_size(16,32);
allow_block_size(16,64);
allow_block_size(32,32);
allow_block_size(32,64);
allow_block_size(64,64);
